# Generated by Django 4.1 on 2024-12-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="cabinet",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("grade_level", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("pass_status", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("time", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "cabinet",
                "managed": False,
            },
        ),
    ]
